### ISSUE TITLE
relativeTo issue

### ISSUE THREAD

**Issue by geddski** [WearyMonkey/ngtemplate-loader#28]
Anytime I try a `relativeTo` path I get this error:

```js
ModuleBuildError: Module build failed:
    at DependenciesBlock.onModuleBuildFailed (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:173:4)
    at nextLoader (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/dave/domo/domoweb/DomoWeb/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

I've tried the following:

```js
loader: "ngtemplate?module=mason&relativeTo=mason!html"

loader: "ngtemplate?module=mason&relativeTo=/public/mason/!html"

loader: "ngtemplate?module=mason&relativeTo="+__dirname +"/public/mason/!html"
```

**Comment by geddski** [comment]
@WearyMonkey any idea what could be causing this issue? I'm blocked on it.
