### ISSUE TITLE
Webpack v3 loaderUtils.parseQuery() deprecation warning

### ISSUE THREAD

**Issue by simshanith** [WearyMonkey/ngtemplate-loader#70]
See webpack/loader-utils#56

When using `webpack 3.5.2` with loader `options` configured instead of `query`:

```
(node:15402) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/plethora/frontend/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/plethora/frontend/node_modules/ngtemplate-loader/index.js:8:29)
    at LOADER_EXECUTION (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/plethora/frontend/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
```

Relevant Configuration:

```js
{
//...
modules: {
  //...
  loaders: [
    //...
    {
      loader: 'ngtemplate-loader',
      options: {
        relativeTo: '/public/',
        prefix: '/',
      },
    },
    //...
  ],
  //...
}
//...
}
```

**Comment by simshanith** [comment]
Everything still works FWIW; just an annoying warning that would need to taken care of here.

**Comment by simshanith** [comment]
Oops, I wasn't yet using v2.0.1. Apologies for my confusion.
